server:
  port: 8081

spring:
  application:
    name: product-service
  datasource:
    url: jdbc:postgresql://dpg-d49l9e3ipnbc73e3i310-a.oregon-postgres.render.com:5432/spectacles_db?sslmode=require
    username: root
    password: 81qRbGXtslfb53oOBlgpxTeQguXXTFMp
    driver-class-name: org.postgresql.Driver
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Eureka Client Configuration
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#  instance:
#    prefer-ip-address: true

# Logging Configuration
#logging:
#  level:
#    org:
#      hibernate: INFO
#      springframework: INFO
#    com.sastachasma: DEBUG

logging:
  pattern:
    console: "%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"